const questions = [
  // Geography (1, 3, 6, 8 + 16 new = 20 total)
  { id: 1, text: "What is the capital of France?", options: ["London", "Berlin", "Paris", "Madrid"], correct: 2, difficulty: 1, category: "Geography" },
  { id: 3, text: "What is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], correct: 2, difficulty: 2, category: "Geography" },
  { id: 6, text: "Which country is home to the Eiffel Tower?", options: ["Germany", "Italy", "France", "Spain"], correct: 2, difficulty: 1, category: "Geography" },
  { id: 8, text: "How many continents are there?", options: ["5", "6", "7", "8"], correct: 2, difficulty: 1, category: "Geography" },
  { id: 101, text: "What is the capital of Japan?", options: ["Osaka", "Tokyo", "Kyoto", "Yokohama"], correct: 1, difficulty: 1, category: "Geography" },
  { id: 102, text: "Which river is the longest in the world?", options: ["Amazon", "Yangtze", "Nile", "Mississippi"], correct: 2, difficulty: 2, category: "Geography" },
  { id: 103, text: "What is the smallest country in the world?", options: ["Monaco", "Liechtenstein", "Vatican City", "San Marino"], correct: 2, difficulty: 2, category: "Geography" },
  { id: 104, text: "Which desert is the largest in the world?", options: ["Sahara", "Arabian", "Gobi", "Antarctic"], correct: 3, difficulty: 3, category: "Geography" },
  { id: 105, text: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], correct: 2, difficulty: 2, category: "Geography" },
  { id: 106, text: "Which mountain range contains Mount Everest?", options: ["Andes", "Himalayas", "Rockies", "Alps"], correct: 1, difficulty: 2, category: "Geography" },
  { id: 107, text: "What is the capital of Canada?", options: ["Toronto", "Vancouver", "Ottawa", "Montreal"], correct: 2, difficulty: 2, category: "Geography" },
  { id: 108, text: "Which country has the most islands?", options: ["Indonesia", "Philippines", "Sweden", "Norway"], correct: 2, difficulty: 3, category: "Geography" },
  { id: 109, text: "What is the deepest ocean trench?", options: ["Challenger Deep", "Mariana Trench", "Philippine Trench", "Tonga Trench"], correct: 0, difficulty: 3, category: "Geography" },
  { id: 110, text: "Which capital is known as the 'City of Canals'?", options: ["Amsterdam", "Venice", "Bangkok", "Stockholm"], correct: 1, difficulty: 2, category: "Geography" },
  { id: 111, text: "What is the capital of South Africa?", options: ["Cape Town", "Johannesburg", "Pretoria", "Durban"], correct: 2, difficulty: 2, category: "Geography" },
  { id: 112, text: "Which strait separates Spain from Morocco?", options: ["Strait of Dover", "Strait of Gibraltar", "Dardanelles", "Bosphorus"], correct: 1, difficulty: 3, category: "Geography" },
  { id: 113, text: "What is the capital of Brazil?", options: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], correct: 2, difficulty: 2, category: "Geography" },
  { id: 114, text: "Which lake is the largest freshwater lake by surface area?", options: ["Lake Superior", "Lake Baikal", "Lake Michigan", "Lake Tanganyika"], correct: 0, difficulty: 3, category: "Geography" },
  { id: 115, text: "What is the capital of Egypt?", options: ["Giza", "Alexandria", "Cairo", "Luxor"], correct: 2, difficulty: 1, category: "Geography" },
  { id: 116, text: "Which country is completely surrounded by South Africa?", options: ["Botswana", "Lesotho", "Zimbabwe", "Namibia"], correct: 1, difficulty: 3, category: "Geography" },

  // Science (2, 5, 10 + 17 new = 20 total)
  { id: 2, text: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Saturn"], correct: 1, difficulty: 1, category: "Science" },
  { id: 5, text: "What is the chemical symbol for gold?", options: ["Go", "Gd", "Au", "Ag"], correct: 2, difficulty: 3, category: "Science" },
  { id: 10, text: "Which element has the atomic number 1?", options: ["Helium", "Hydrogen", "Lithium", "Carbon"], correct: 1, difficulty: 2, category: "Science" },
  { id: 201, text: "What is the chemical symbol for silver?", options: ["Sl", "Si", "Ag", "S"], correct: 2, difficulty: 2, category: "Science" },
  { id: 202, text: "How many bones are in the adult human body?", options: ["186", "206", "226", "246"], correct: 1, difficulty: 2, category: "Science" },
  { id: 203, text: "What gas do plants absorb from the atmosphere?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Helium"], correct: 2, difficulty: 1, category: "Science" },
  { id: 204, text: "What is the speed of light in vacuum?", options: ["300,000 km/s", "150,000 km/s", "450,000 km/s", "200,000 km/s"], correct: 0, difficulty: 3, category: "Science" },
  { id: 205, text: "Which scientist developed the theory of evolution?", options: ["Gregor Mendel", "Charles Darwin", "Louis Pasteur", "Isaac Newton"], correct: 1, difficulty: 2, category: "Science" },
  { id: 206, text: "What is the most abundant element in the universe?", options: ["Oxygen", "Carbon", "Helium", "Hydrogen"], correct: 3, difficulty: 2, category: "Science" },
  { id: 207, text: "How many chambers does a human heart have?", options: ["2", "3", "4", "5"], correct: 2, difficulty: 2, category: "Science" },
  { id: 208, text: "What is the smallest unit of life?", options: ["Atom", "Molecule", "Cell", "Organ"], correct: 2, difficulty: 1, category: "Science" },
  { id: 209, text: "What does DNA stand for?", options: ["Deoxyribonucleic acid", "Diribonucleic acid", "Deoxyribose nucleic acid", "Deoxyribonuclear acid"], correct: 0, difficulty: 3, category: "Science" },
  { id: 210, text: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], correct: 1, difficulty: 1, category: "Science" },
  { id: 211, text: "What is the boiling point of water at sea level?", options: ["90°C", "100°C", "110°C", "120°C"], correct: 1, difficulty: 1, category: "Science" },
  { id: 212, text: "What type of animal is a dolphin?", options: ["Fish", "Mammal", "Amphibian", "Reptile"], correct: 1, difficulty: 2, category: "Science" },
  { id: 213, text: "How many planets are in our solar system?", options: ["7", "8", "9", "10"], correct: 1, difficulty: 1, category: "Science" },
  { id: 214, text: "What is the SI unit of force?", options: ["Watt", "Joule", "Newton", "Pascal"], correct: 2, difficulty: 3, category: "Science" },
  { id: 215, text: "What is the process by which plants convert sunlight to energy?", options: ["Respiration", "Fermentation", "Photosynthesis", "Combustion"], correct: 2, difficulty: 2, category: "Science" },
  { id: 216, text: "How many chromosomes does a human cell have?", options: ["23", "46", "92", "69"], correct: 1, difficulty: 3, category: "Science" },

  // History (7 + 19 new = 20 total)
  { id: 7, text: "What year did the Titanic sink?", options: ["1912", "1920", "1898", "1925"], correct: 0, difficulty: 2, category: "History" },
  { id: 301, text: "In what year did World War II end?", options: ["1943", "1944", "1945", "1946"], correct: 2, difficulty: 1, category: "History" },
  { id: 302, text: "Who was the first President of the United States?", options: ["Thomas Jefferson", "George Washington", "John Adams", "James Madison"], correct: 1, difficulty: 1, category: "History" },
  { id: 303, text: "In what year did Christopher Columbus reach the Americas?", options: ["1490", "1491", "1492", "1493"], correct: 2, difficulty: 2, category: "History" },
  { id: 304, text: "Which ancient wonder is still standing today?", options: ["Hanging Gardens", "Great Pyramid of Giza", "Colossus of Rhodes", "Lighthouse of Alexandria"], correct: 1, difficulty: 2, category: "History" },
  { id: 305, text: "In what year did the Berlin Wall fall?", options: ["1987", "1988", "1989", "1990"], correct: 2, difficulty: 2, category: "History" },
  { id: 306, text: "Who was the first person to walk on the moon?", options: ["Buzz Aldrin", "Neil Armstrong", "John Glenn", "Yuri Gagarin"], correct: 1, difficulty: 1, category: "History" },
  { id: 307, text: "In what year did the Magna Carta get signed?", options: ["1115", "1215", "1315", "1415"], correct: 1, difficulty: 3, category: "History" },
  { id: 308, text: "Who led the Russian Revolution?", options: ["Stalin", "Trotsky", "Lenin", "Khrushchev"], correct: 2, difficulty: 2, category: "History" },
  { id: 309, text: "In what year did the American Civil War end?", options: ["1862", "1863", "1864", "1865"], correct: 3, difficulty: 2, category: "History" },
  { id: 310, text: "Who was the longest-reigning British monarch before 2022?", options: ["Queen Victoria", "King George III", "Queen Elizabeth II", "King Edward VII"], correct: 2, difficulty: 2, category: "History" },
  { id: 311, text: "In what year did the Titanic sink?", options: ["1910", "1911", "1912", "1913"], correct: 2, difficulty: 1, category: "History" },
  { id: 312, text: "Who wrote the Declaration of Independence?", options: ["John Adams", "Benjamin Franklin", "Thomas Jefferson", "James Madison"], correct: 2, difficulty: 2, category: "History" },
  { id: 313, text: "In what year did the Byzantine Empire fall?", options: ["1423", "1453", "1483", "1513"], correct: 1, difficulty: 3, category: "History" },
  { id: 314, text: "Who was Napoleon Bonaparte?", options: ["German general", "French military leader", "Russian czar", "Spanish conquistador"], correct: 1, difficulty: 2, category: "History" },
  { id: 315, text: "In what year did the American Revolution begin?", options: ["1773", "1774", "1775", "1776"], correct: 2, difficulty: 2, category: "History" },
  { id: 316, text: "Who invented the printing press?", options: ["Johannes Gutenberg", "Galileo Galilei", "Leonardo da Vinci", "Nicolaus Copernicus"], correct: 0, difficulty: 2, category: "History" },
  { id: 317, text: "In what year did Pearl Harbor get attacked?", options: ["1940", "1941", "1942", "1943"], correct: 1, difficulty: 2, category: "History" },
  { id: 318, text: "Who was the first female Prime Minister of the UK?", options: ["Barbara Castle", "Margaret Thatcher", "Theresa May", "Elizabeth Windsor"], correct: 1, difficulty: 2, category: "History" },
  { id: 319, text: "In what century did the Renaissance occur?", options: ["13th-14th", "14th-17th", "15th-18th", "16th-19th"], correct: 1, difficulty: 3, category: "History" },

  // Literature (4 + 19 new = 20 total)
  { id: 4, text: "Who wrote 'Romeo and Juliet'?", options: ["Jane Austen", "William Shakespeare", "Mark Twain", "Charles Dickens"], correct: 1, difficulty: 2, category: "Literature" },
  { id: 401, text: "Who wrote 'Pride and Prejudice'?", options: ["Charlotte Brontë", "Jane Austen", "Emily Dickinson", "George Eliot"], correct: 1, difficulty: 2, category: "Literature" },
  { id: 402, text: "Who wrote 'To Kill a Mockingbird'?", options: ["Harper Lee", "Flannery O'Connor", "Carson McCullers", "Eudora Welty"], correct: 0, difficulty: 2, category: "Literature" },
  { id: 403, text: "Who wrote '1984'?", options: ["Isaac Asimov", "George Orwell", "Ray Bradbury", "Arthur C. Clarke"], correct: 1, difficulty: 1, category: "Literature" },
  { id: 404, text: "Who wrote 'The Great Gatsby'?", options: ["Ernest Hemingway", "F. Scott Fitzgerald", "William Faulkner", "Sinclair Lewis"], correct: 1, difficulty: 2, category: "Literature" },
  { id: 405, text: "Who wrote 'Moby Dick'?", options: ["Herman Melville", "Nathaniel Hawthorne", "Henry David Thoreau", "Ralph Waldo Emerson"], correct: 0, difficulty: 2, category: "Literature" },
  { id: 406, text: "Who wrote 'Jane Eyre'?", options: ["Charlotte Brontë", "Emily Brontë", "Anne Brontë", "George Eliot"], correct: 0, difficulty: 2, category: "Literature" },
  { id: 407, text: "Who wrote 'The Odyssey'?", options: ["Hesiod", "Homer", "Sophocles", "Aeschylus"], correct: 1, difficulty: 3, category: "Literature" },
  { id: 408, text: "Who wrote 'Wuthering Heights'?", options: ["Charlotte Brontë", "Emily Brontë", "Anne Brontë", "George Eliot"], correct: 1, difficulty: 3, category: "Literature" },
  { id: 409, text: "Who wrote 'The Catcher in the Rye'?", options: ["Kurt Vonnegut", "J.D. Salinger", "Aldous Huxley", "Jack Kerouac"], correct: 1, difficulty: 2, category: "Literature" },
  { id: 410, text: "Who wrote 'Crime and Punishment'?", options: ["Tolstoy", "Dostoevsky", "Pushkin", "Turgenev"], correct: 1, difficulty: 3, category: "Literature" },
  { id: 411, text: "Who wrote 'The Tale of Two Cities'?", options: ["Charles Dickens", "George Eliot", "William Thackeray", "Anthony Trollope"], correct: 0, difficulty: 2, category: "Literature" },
  { id: 412, text: "Who wrote 'Frankenstein'?", options: ["Mary Shelley", "Bram Stoker", "H.G. Wells", "Jules Verne"], correct: 0, difficulty: 2, category: "Literature" },
  { id: 413, text: "Who wrote 'The Picture of Dorian Gray'?", options: ["Oscar Wilde", "George Bernard Shaw", "W.B. Yeats", "Samuel Beckett"], correct: 0, difficulty: 3, category: "Literature" },
  { id: 414, text: "Who wrote 'Anna Karenina'?", options: ["Turgenev", "Tolstoy", "Dostoevsky", "Pushkin"], correct: 1, difficulty: 3, category: "Literature" },
  { id: 415, text: "Who wrote 'The Brothers Karamazov'?", options: ["Tolstoy", "Dostoevsky", "Turgenev", "Pushkin"], correct: 1, difficulty: 3, category: "Literature" },
  { id: 416, text: "Who wrote 'Hamlet'?", options: ["Christopher Marlowe", "William Shakespeare", "Ben Jonson", "Thomas Kyd"], correct: 1, difficulty: 2, category: "Literature" },
  { id: 417, text: "Who wrote 'The Odyssey' and 'The Iliad'?", options: ["Hesiod", "Homer", "Sophocles", "Aeschylus"], correct: 1, difficulty: 2, category: "Literature" },
  { id: 418, text: "Who wrote 'Ulysses'?", options: ["Samuel Beckett", "James Joyce", "Virginia Woolf", "D.H. Lawrence"], correct: 1, difficulty: 3, category: "Literature" },
  { id: 419, text: "Who wrote 'One Hundred Years of Solitude'?", options: ["Jorge Luis Borges", "Gabriel García Márquez", "Mario Vargas Llosa", "Carlos Fuentes"], correct: 1, difficulty: 3, category: "Literature" },

  // Math (9 + 19 new = 20 total)
  { id: 9, text: "What is the smallest prime number?", options: ["0", "1", "2", "3"], correct: 2, difficulty: 3, category: "Math" },
  { id: 501, text: "What is 7 × 8?", options: ["54", "56", "58", "60"], correct: 1, difficulty: 1, category: "Math" },
  { id: 502, text: "What is the square root of 144?", options: ["10", "11", "12", "13"], correct: 2, difficulty: 1, category: "Math" },
  { id: 503, text: "What is 15% of 100?", options: ["10", "15", "20", "25"], correct: 1, difficulty: 1, category: "Math" },
  { id: 504, text: "What is the value of π (pi) rounded to 2 decimal places?", options: ["3.12", "3.14", "3.16", "3.18"], correct: 1, difficulty: 2, category: "Math" },
  { id: 505, text: "How many degrees are in a right angle?", options: ["45", "90", "180", "360"], correct: 1, difficulty: 1, category: "Math" },
  { id: 506, text: "What is the area of a circle with radius 5?", options: ["25π", "50π", "75π", "100π"], correct: 0, difficulty: 3, category: "Math" },
  { id: 507, text: "What is 2^5?", options: ["16", "32", "64", "128"], correct: 1, difficulty: 1, category: "Math" },
  { id: 508, text: "What is the sum of angles in a triangle?", options: ["90°", "180°", "270°", "360°"], correct: 1, difficulty: 1, category: "Math" },
  { id: 509, text: "What is the greatest common divisor of 12 and 18?", options: ["2", "3", "6", "9"], correct: 2, difficulty: 2, category: "Math" },
  { id: 510, text: "What is 1/2 + 1/4?", options: ["1/6", "2/4", "3/4", "5/4"], correct: 2, difficulty: 2, category: "Math" },
  { id: 511, text: "What is the derivative of x²?", options: ["x", "2x", "x³", "2"], correct: 1, difficulty: 3, category: "Math" },
  { id: 512, text: "What is the Fibonacci sequence's 6th number?", options: ["5", "8", "13", "21"], correct: 1, difficulty: 2, category: "Math" },
  { id: 513, text: "How many sides does a pentagon have?", options: ["4", "5", "6", "7"], correct: 1, difficulty: 1, category: "Math" },
  { id: 514, text: "What is the solution to x + 5 = 12?", options: ["5", "7", "12", "17"], correct: 1, difficulty: 1, category: "Math" },
  { id: 515, text: "What is the volume of a cube with side length 3?", options: ["9", "18", "27", "36"], correct: 2, difficulty: 2, category: "Math" },
  { id: 516, text: "What is 25% of 80?", options: ["15", "20", "25", "30"], correct: 1, difficulty: 1, category: "Math" },
  { id: 517, text: "What is the factorial of 5 (5!)?", options: ["20", "60", "120", "240"], correct: 2, difficulty: 2, category: "Math" },
  { id: 518, text: "What is log₁₀(100)?", options: ["1", "2", "10", "100"], correct: 1, difficulty: 3, category: "Math" },
  { id: 519, text: "What is the probability of rolling a 6 on a standard die?", options: ["1/4", "1/6", "1/3", "1/2"], correct: 1, difficulty: 2, category: "Math" }
];

// Shuffle an array in-place (Fisher-Yates)
function shuffleArray(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}
